import Image from "next/image"
import { Button, HTag, Tag } from "../components"
import Head from "next/head"
import vercel from "../../public/vercel.svg"
import PTag from "@/components/PTag/PTag"
export default function Home(): JSX.Element {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Image src={vercel} alt='Vercel Logo' />
				<HTag tag='h1'>Text</HTag>
				<Button appearance='primary'>Button 1</Button>
				<Button appearance='ghost'>Button 2</Button>

				<PTag size='large'>Text</PTag>
				<PTag size='medium'>Text</PTag>
				<PTag size='small'>Text</PTag>
				<Tag size='s' color='red'>
					tag
				</Tag>
				<Tag size='m' color='green'>
					tag
				</Tag>
				<Tag size='m' color='gray'>
					tag
				</Tag>
				<Tag size='s' color='primary'>
					tag
				</Tag>
				<Tag size='m' color='ghost'>
					tag
				</Tag>
				<Tag size='s' color='ghost'>
					tag
				</Tag>
			</main>
		</>
	)
}
